# Generated by Django 3.0.8 on 2020-10-27 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginDB', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('files', models.FileField(upload_to='')),
            ],
        ),
    ]
