# Generated by Django 3.1.4 on 2020-12-06 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoginDB', '0002_files'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='users',
            unique_together=set(),
        ),
    ]
