# Generated by Django 3.1.4 on 2020-12-06 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoginDB', '0003_auto_20201206_1730'),
        ('LoginDB', '0003_auto_20201206_1720'),
    ]

    operations = [
    ]
